Handling MIssing Values
-   `df.isnull()` - to detect missing values (`.isna()` is the same thing)
-   `df.fillna()` - to fill missing values (imputation)
-   `df.dropna()` - to remove missing values
-   `df.replace()`-  to replace specific values (imputation)

In [1]:
import numpy as np
import pandas as pd

In [2]:
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Adam', 40, np.nan, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['lynda', 42, 85, np.nan],
               [np.nan, 42, 85, np.nan],
               ['Jenny', np.nan, 100, 25632],
               ['Kenn', np.nan, 110, 25632],
                ['Aly', np.nan, 90, 25582],
               ['John', 41, 85, 1528000]]

employee_df = pd.DataFrame(employee_list, columns=['Name', 'Age', 'Weight', 'Salary'])

In [3]:
rows, columns = employee_df.shape
print(f'The number of rows is {rows} and the number of columns is {columns}')

The number of rows is 14 and the number of columns is 4

In [5]:
employee_df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [6]:
employee_df.isnull().sum()

Name      1
Age       3
Weight    1
Salary    2
dtype: int64

In [7]:
# be weary of the missing values in the DataFrame. It can cause problems when we are doing data analysis and machine learning. 
dropped_employee_df = employee_df.dropna()
print(dropped_employee_df)

        Name   Age  Weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
13      John  41.0    85.0  1528000.0

In [8]:
filled_employee_df = employee_df.fillna(0)
print(filled_employee_df)

        Name   Age  Weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
5       Adam  40.0     0.0  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
8      lynda  42.0    85.0        0.0
9          0  42.0    85.0        0.0
10     Jenny   0.0   100.0    25632.0
11      Kenn   0.0   110.0    25632.0
12       Aly   0.0    90.0    25582.0
13      John  41.0    85.0  1528000.0

In [9]:
filled_employee_df.isnull().sum()

Name      0
Age       0
Weight    0
Salary    0
dtype: int64

In [16]:
employee_df2 = employee_df.fillna(value={'Weight': 'Pending', 'Age': 'Unknown', 'Salary': '0.0', 'Name': 'Verification Pending'})
print(employee_df2)

                    Name      Age   Weight     Salary
0                  James     36.0     75.0  5428000.0
1                Villers     38.0     74.0  3428000.0
2                  VKole     31.0     70.0  8428000.0
3                  Smith     34.0     80.0  4428000.0
4                  Gayle     40.0    100.0  4528000.0
5                   Adam     40.0  Pending  4528000.0
6                 Rooter     33.0     72.0  7028000.0
7               Peterson     42.0     85.0  2528000.0
8                  lynda     42.0     85.0        0.0
9   Verification Pending     42.0     85.0        0.0
10                 Jenny  Unknown    100.0    25632.0
11                  Kenn  Unknown    110.0    25632.0
12                   Aly  Unknown     90.0    25582.0
13                  John     41.0     85.0  1528000.0

In [17]:
technologies = {
    'Courses':["Spark",np.nan,"Hadoop","Python","pandas",np.nan,"Java"],
    'Fee' :[20000,25000, np.nan,22000,24000,np.nan,22000],
    'Duration':[np.nan,'40days','35days', np.nan,'60days','50days','55days'],
    'Discount':[1000,np.nan,1500,np.nan,2500,2100,np.nan]
              }

tech=pd.DataFrame(technologies)
print(tech)

  Courses      Fee Duration  Discount
0   Spark  20000.0      NaN    1000.0
1     NaN  25000.0   40days       NaN
2  Hadoop      NaN   35days    1500.0
3  Python  22000.0      NaN       NaN
4  pandas  24000.0   60days    2500.0
5     NaN      NaN   50days    2100.0
6    Java  22000.0   55days       NaN

In [18]:
rows, columns = tech.shape
print(f'The number of rows is {rows} and the number of columns is {columns}')

The number of rows is 7 and the number of columns is 4

In [19]:
tech.isnull().sum()

Courses     2
Fee         2
Duration    2
Discount    3
dtype: int64

In [20]:
tech

  Courses      Fee Duration  Discount
0   Spark  20000.0      NaN    1000.0
1     NaN  25000.0   40days       NaN
2  Hadoop      NaN   35days    1500.0
3  Python  22000.0      NaN       NaN
4  pandas  24000.0   60days    2500.0
5     NaN      NaN   50days    2100.0
6    Java  22000.0   55days       NaN

In [22]:
tech2=tech.replace(np.nan, '')
print(tech2)

  Courses      Fee Duration Discount
0   Spark  20000.0            1000.0
1          25000.0   40days
2  Hadoop            35days   1500.0
3  Python  22000.0
4  pandas  24000.0   60days   2500.0
5                    50days   2100.0
6    Java  22000.0   55days

In [23]:
tech3=tech.replace({'Courses': np.nan, 'Fee': np.nan, 'Duration': np.nan, 'Discount': np.nan})
print(tech3)

  Courses      Fee Duration  Discount
0   Spark  20000.0      NaN    1000.0
1     NaN  25000.0   40days       NaN
2  Hadoop      NaN   35days    1500.0
3  Python  22000.0      NaN       NaN
4  pandas  24000.0   60days    2500.0
5     NaN      NaN   50days    2100.0
6    Java  22000.0   55days       NaN

In [24]:
tech.fillna('')
tech

  Courses      Fee Duration  Discount
0   Spark  20000.0      NaN    1000.0
1     NaN  25000.0   40days       NaN
2  Hadoop      NaN   35days    1500.0
3  Python  22000.0      NaN       NaN
4  pandas  24000.0   60days    2500.0
5     NaN      NaN   50days    2100.0
6    Java  22000.0   55days       NaN

In [27]:
employee_df=pd.read_csv('data/employee.csv')
employee_df

        Name   Age  Weight     Salary
0      James  36.0    75.0  5428000.0
1    Villers  38.0    74.0  3428000.0
2      VKole  31.0    70.0  8428000.0
3      Smith  34.0    80.0  4428000.0
4      Gayle  40.0   100.0  4528000.0
5       Adam  40.0     NaN  4528000.0
6     Rooter  33.0    72.0  7028000.0
7   Peterson  42.0    85.0  2528000.0
8      lynda  42.0    85.0        NaN
9        NaN  42.0    85.0        NaN
10     Jenny   NaN   100.0    25632.0
11      Kenn   NaN   110.0    25632.0
12       Aly   NaN    90.0    25582.0
13      John  41.0    85.0  1528000.0
14       Ali  26.0    69.0        NaN

In [28]:
employee_df.isnull().sum()

Name      1
Age       3
Weight    1
Salary    3
dtype: int64

In [29]:
employee_df=employee_df.fillna({'name': 'Unknown', 'Age': 'Unknown', 'Weight': 'Pending', 'Salary': '0.0'})
employee_df

        Name      Age   Weight     Salary
0      James     36.0     75.0  5428000.0
1    Villers     38.0     74.0  3428000.0
2      VKole     31.0     70.0  8428000.0
3      Smith     34.0     80.0  4428000.0
4      Gayle     40.0    100.0  4528000.0
5       Adam     40.0  Pending  4528000.0
6     Rooter     33.0     72.0  7028000.0
7   Peterson     42.0     85.0  2528000.0
8      lynda     42.0     85.0        0.0
9        NaN     42.0     85.0        0.0
10     Jenny  Unknown    100.0    25632.0
11      Kenn  Unknown    110.0    25632.0
12       Aly  Unknown     90.0    25582.0
13      John     41.0     85.0  1528000.0
14       Ali     26.0     69.0        0.0