In [27]:
import numpy as np
import pandas as pd

In [28]:
url = 'https://raw.githubusercontent.com/bprasad26/lwd/master/data/tesla_stock_prices.csv'
tesla_df = pd.read_csv(url)
tesla_df.head()

         Date       Open   High        Low      Close  Adj Close    Volume
0  2010-06-29  19.000000  25.00  17.540001  23.889999  23.889999  18766300
1  2010-06-30  25.790001  30.42  23.299999  23.830000  23.830000  17187100
2  2010-07-01  25.000000  25.92  20.270000  21.959999  21.959999   8218800
3  2010-07-02  23.000000  23.10  18.709999  19.200001  19.200001   5139800
4  2010-07-06  20.000000  20.00  15.830000  16.110001  16.110001   6866900

In [29]:
url = 'https://raw.githubusercontent.com/bprasad26/lwd/master/data/tesla_stock_prices.csv'
tesla_df = pd.read_csv(url, parse_dates=['Date'])      
tesla_df.head()

        Date       Open   High        Low      Close  Adj Close    Volume
0 2010-06-29  19.000000  25.00  17.540001  23.889999  23.889999  18766300
1 2010-06-30  25.790001  30.42  23.299999  23.830000  23.830000  17187100
2 2010-07-01  25.000000  25.92  20.270000  21.959999  21.959999   8218800
3 2010-07-02  23.000000  23.10  18.709999  19.200001  19.200001   5139800
4 2010-07-06  20.000000  20.00  15.830000  16.110001  16.110001   6866900

In [30]:
tesla_df['month'] = tesla_df['Date'].dt.month
tesla_df['day_of_month  '] = tesla_df['Date'].dt.day
tesla_df['year'] = tesla_df['Date'].dt.year 

tesla_df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,month,day_of_month,year
0,2010-06-29,19.000000,25.00,17.540001,23.889999,23.889999,18766300,6,29,2010
1,2010-06-30,25.790001,30.42,23.299999,23.830000,23.830000,17187100,6,30,2010
2,2010-07-01,25.000000,25.92,20.270000,21.959999,21.959999,8218800,7,1,2010
3,2010-07-02,23.000000,23.10,18.709999,19.200001,19.200001,5139800,7,2,2010
4,2010-07-06,20.000000,20.00,15.830000,16.110001,16.110001,6866900,7,6,2010

In [31]:
# Add new columns to dataframe based off of dates
tesla_df['Day'] = tesla_df['Date'].dt.day
tesla_df['Month'] = tesla_df['Date'].dt.month
tesla_df['Year'] = tesla_df['Date'].dt.year
tesla_df['day_name'] = tesla_df['Date'].dt.day_name()

tesla_df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume,month,day_of_month,year,Day,Month,Year,day_name
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,6,29,2010,29,6,2010,Tuesday
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,6,30,2010,30,6,2010,Wednesday
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,7,1,2010,1,7,2010,Thursday
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,7,2,2010,2,7,2010,Friday
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,7,6,2010,6,7,2010,Tuesday
5,2010-07-07,16.400000,16.629999,14.980000,15.800000,15.800000,6921700,7,7,2010,7,7,2010,Wednesday
6,2010-07-08,16.139999,17.520000,15.570000,17.459999,17.459999,7711400,7,8,2010,8,7,2010,Thursday
7,2010-07-09,17.580000,17.900000,16.549999,17.400000,17.400000,4050600,7,9,2010,9,7,2010,Friday
8,2010-07-12,17.950001,18.070000,17.000000,17.049999,17.049999,2202500,7,12,2010,12,7,2010,Monday
9,2010-07-13,17.389999,18.639999,16.900000,18.139999,18.139999,2680100,7,13,2010,13,7,2010,Tuesday

In [32]:
least_recent_date = tesla_df['Date'].min()
most_recent_date= tesla_df[tesla_df['Date']== tesla_df['Date'].max()]['Date'].values[0]     
print(most_recent_date)
print(least_recent_date)

2017-08-08T00:00:00.000000
2010-06-29 00:00:00

In [33]:
monthly_sales = tesla_df.groupby(['month', 'year'])['Volume'].sum().reset_index()
monthly_sales.head(15)

    month  year     Volume
0       1  2011   28420100
1       1  2012   25609900
2       1  2013   28464600
3       1  2014  183932300
4       1  2015   90167100
5       1  2016   78990800
6       1  2017  100679600
7       2  2011   29303500
8       2  2012   23193600
9       2  2013   44256000
10      2  2014  225954100
11      2  2015  106717500
12      2  2016  133705800
13      2  2017  119540000
14      3  2011   32563300

In [34]:
## Filtering using Loc or Query
filtered_df = tesla_df.loc[tesla_df['Date'] >= '2020-08-01']
filtered_df_date = tesla_df.query('Date >= "2020-08-01"')
filtered_df.head()

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Adj Close, Volume, month, day_of_month  , year, Day, Month, Year, day_name]
Index: []